source: app
destination: app/_site

# Site settings
title: Pere Albujer
subtitle: El éxito depende del esfuerzo
description: > # this means to ignore newlines until "baseurl:"

author: Pere Albujer
email: pere@albujer.com

baseurl: "" # the subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
url: "http://albujer.com" # the base hostname & protocol for your site

twitter_username: 'P4R93'
github_username:  P4R
paypal_donations: http://paypal.me/PAlbujer
disqus_shortname: 
google_analytics: ''

# Pagination
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

collections:
  projects:
    permalink: /projects/:year/:month/:day/:title/
    output: true

# Archive settings
jekyll-archives:
  enabled: ['tags']