source: app
destination: app/_site

# Site settings
title: Pere Albujer
subtitle: El éxito depende del esfuerzo
description: Página web de Pere Albujer | El éxito depende del esfuerzo

author: Pere Albujer

# Emails are in three parts for prevent scrapers. Emails will be loaded using JS.
# Email Form -> IMPORTANT if principal email is not set, set published to false in contact.html
email_1: pere
email_2: albujer
email_3: com
# Email CC
email_cc_1: p4r.esp
email_cc_2: gmail
email_cc_3: com

baseurl: "" # the subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
url: "http://albujer.com" # the base hostname & protocol for your site

twitter_username: 'P4R93'
github_username:  P4R
paypal_donations: http://paypal.me/PAlbujer
disqus_shortname: 
google_analytics: UA-75892687-1

# Pagination
paginate: 5
paginate_path: "blog/page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

collections:
  projects:
    permalink: /projects/:year/:month/:day/:title/
    output: true

# Archive settings
jekyll-archives:
  enabled: ['tags']